// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmJGRgBMwBjk9bRprlr9-4tu-wsrgalKg',
    appId: '1:81476290675:web:9a05bc46a22a059ad7c206',
    messagingSenderId: '81476290675',
    projectId: 'saathitravelcheck',
    authDomain: 'saathitravelcheck.firebaseapp.com',
    storageBucket: 'saathitravelcheck.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD689ttHY8ItX7H757vC1lz8usWAvDrfnY',
    appId: '1:81476290675:android:26215a3d8d86e357d7c206',
    messagingSenderId: '81476290675',
    projectId: 'saathitravelcheck',
    storageBucket: 'saathitravelcheck.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBav77TggVRHsFx9TqclbEAiaqviLSbrk8',
    appId: '1:81476290675:ios:b8faa93c94a29d53d7c206',
    messagingSenderId: '81476290675',
    projectId: 'saathitravelcheck',
    storageBucket: 'saathitravelcheck.appspot.com',
    iosBundleId: 'com.example.saathiTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBav77TggVRHsFx9TqclbEAiaqviLSbrk8',
    appId: '1:81476290675:ios:69091f5d3d21c6f6d7c206',
    messagingSenderId: '81476290675',
    projectId: 'saathitravelcheck',
    storageBucket: 'saathitravelcheck.appspot.com',
    iosBundleId: 'com.example.saathiTask.RunnerTests',
  );
}
